jobs:
  - job: Linux
    strategy:
      matrix:
        node_8_x:
          nodeVersion: 8.x
        node_9_x:
          nodeVersion: 9.x
        node_10_x:
          nodeVersion: 10.x
        node_11_x:
          nodeVersion: 11.x
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: azure-pipelines-steps.yml
        parameters:
          nodeVersion: $(nodeVersion)

  - job: macOS
    strategy:
      matrix:
        node_8_x:
          nodeVersion: 8.x
        node_9_x:
          nodeVersion: 9.x
        node_10_x:
          nodeVersion: 10.x
        node_11_x:
          nodeVersion: 11.x
    pool:
      vmImage: macos-10.13
    steps:
      - template: azure-pipelines-steps.yml
        parameters:
          nodeVersion: $(nodeVersion)

  - job: Windows
    strategy:
      matrix:
        node_8_x:
          nodeVersion: 8.x
        node_9_x:
          nodeVersion: 9.x
        node_10_x:
          nodeVersion: 10.x
        node_11_x:
          nodeVersion: 11.x
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: azure-pipelines-steps.yml
        parameters:
          nodeVersion: $(nodeVersion)
