pool:
  vmImage: Ubuntu-16.04

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_9_x:
      node_version: 9.x
    node_10_x:
      node_version: 10.x
    node_11_x:
      node_version: 11.x

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: $(node_version)

  - script: yarn install
    displayName: Install dependencies

  - script: yarn build
    displayName: Build application

  - script: yarn test:ci
    displayName: Running tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: Test results for JavaScript
    condition: succeededOrFailed()
