jobs:
  - template: pipelines/jobs.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04

  - template: pipelines/jobs.yml
    parameters:
      name: macOS
      vmImage: macos-10.13

  - template: pipelines/jobs.yml
    parameters:
      name: Windows
      vmImage: vs2017-win2016
